### ISSUE TITLE
Add aria-label to nav element

### ISSUE THREAD

**Issue by cadie** [UCF/Section-Menus-Shortcode#12]
This came up as an issue for a page on the Admissions site in SiteImprove:

> **Description of this issue:**
> The page contains two or more HTML5 or WAI-ARIA landmarks of the same type that has not been named. Users might not know the difference if it's not somehow explained.
> **How to fix it:**
> Use the WAI-ARIA attributes 'aria-label' or 'aria-labelledby' to create unique names that describe the purpose of each landmark.

It's an issue when the header nav element and section menu nav element are both on a page. To solve this we could add an aria-label to the `nav` element that echos out the page title plus "Section Navigation" to differentiate it from the main nav. 

https://github.com/UCF/Section-Menus-Shortcode/blob/3e21c2dea354e4140f555786a7128c7446edc6e9/includes/sections-menu-common.php#L100

**Comment by cjg89** [comment]
Resolved in v1.1.1.
