### ISSUE TITLE
Option to Link to External Pages

### ISSUE THREAD

**Issue by cohpa** [UCF/Section-Menus-Shortcode#9]
Would love to be able to have links that also could link out to external pages within this section. 

Something like if you added within the section code:
url="https://google" newtab="true"

So... 
section id="physiologylab" class="auto-section" data-section-link-title="Applied Physiology Lab" role="region" aria-label="Applied Physiology Lab" url="https://google" newtab="true"

This would then trigger and if !empty statement that allowed the link to link out to another external page instead of just an anchor on the page.

**Comment by cjg89** [comment]
Feature has been added in v1.1.0; see https://github.com/UCF/Section-Menus-Shortcode/releases/tag/v1.1.0 for details.
